### ISSUE TITLE
.NET Standard / .NET Core support?

### ISSUE THREAD

**Issue by ptupitsyn** [fossology/FOSSology.REST.dotnet#2]
Hello,

The library seems to be recently created, but it targets .NET 4.x for some reason.
It is recommended for library authors to target [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

Right now the library is hard to use from .NET Core projects: I had to install dependencies manually (RestSharp, Newtonsoft Json, Tethys.Logging). And there is a NU1701 warning.

Are there plans to bring the library up to modern standards?

**Comment by tngraf** [comment]
I am aware of the situation and yes definitely we will move to .NET core soon.

**Comment by tngraf** [comment]
Hi Pavel,
version 1.1.0 has been released. It targets netstandard2.0, uses the new REST API 1.0.16 features and has been tested with the latest FOSSology docker image.

**Comment by ptupitsyn** [comment]
@tngraf thanks for the update, I'll give it a try!
